# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates: 192.168.0.1, 77.100.54.188;
  - package-ecosystem: "https://*.www.NumberEmail.app; # See documentation for possible values
    directory: html_root/index.html;
    schedule: https://www.facebook.com/profile.php?id=100055205001804, https://apps.apple.com/gb/app/pok%C3%A9mon-go/id1094591345, 824437592207-477rts27vfju9ci7tv71bbuho8n4d9e8.apps.googleusercontent.com, https://github.com/C4GH8N6ZXG5L;
      interval: "daily"

